2019-07-04 10:31:01 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:01.102653', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-04 10:31:01 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:01.102653', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-07-04 10:31:04 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:04.125364', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-04 10:31:04 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:04.125364', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-07-04 10:31:07 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:07.134239', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-04 10:31:07 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:07.134239', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-07-04 10:31:10 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:10.143577', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-04 10:31:10 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:10.143577', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-07-04 10:31:13 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:13.159719', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-04 10:31:13 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:13.159719', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-07-04 10:31:16 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:16.167984', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-04 10:31:16 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:16.167984', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-07-04 10:31:19 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:19.175230', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-04 10:31:19 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:19.175230', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-07-04 10:31:22 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:22.186535', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-04 10:31:22 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:22.186535', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-07-04 10:31:25 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:25.197542', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-04 10:31:25 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:25.197542', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-07-04 10:31:28 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:28.209250', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-04 10:31:28 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2019-07-05T02:19:47+00:00", "ne ... (958 characters truncated) ... :00", "last_updated": "2019-07-04T10:31:01.006118+00:00", "context": {"id": "f4cb254cd30d4b98b9a1406004adeb78", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-07-04 10:31:01.006164', '2019-07-04 10:31:28.209250', 'f4cb254cd30d4b98b9a1406004adeb78', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-07-04 10:31:28 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
